[build-system]
requires = ["maturin ~= 0.14"]
build-backend = "maturin"

[project]
name = "robyn"
version = "0.24.1"
description = "A web server that is fast!"
authors = [
  { name = "Sanskar Jethi", email = "sansyrox@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
keywords = ["web", "framework", "development"]
dependencies = [
  "watchdog ~= 2.2",
  "multiprocess ~= 0.70",
# conditional
  "uvloop ~= 0.17; platform_system != 'Windows'",
]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Environment :: Web Environment",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: BSD License",
  "Operating System :: OS Independent",
  "Topic :: Internet :: WWW/HTTP",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
]

[project.urls]
"Source Code" = "https://github.com/sansyrox/robyn"
"Issues" = "https://github.com/sansyrox/robyn/issues"
"Documentation" = "https://robyn.tech/"

[project.optional-dependencies]
dev = [
  "maturin ~= 0.14",
  "ruff ~= 0.0",
  "black ~= 23.1",
  "isort ~= 5.12",
  "pre-commit ~= 3.0",
  "commitizen ~= 2.40",
  "pip-tools ~= 6.12"
]
test = [
  "requests ~= 2.28",
  "pytest ~= 7.2",
  "websocket-client ~= 1.5",
]
templating = [
  "jinja2 ~= 3.1"
]

[tool.ruff]
line-length = 160
exclude = ["src/*" , ".git" , "docs"]

[tool.ruff.mccabe]
max-complexity = 10
